resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /websphere-traditional-operator-system/operator
  newTag: latest
- name: controller
  newName: image-registry.openshift-image-registry.svc:5000/websphere-traditional-operator-system/operator
  newTag: latest
