# permissions for end users to view webspheretraditionalapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webspheretraditionalapplication-viewer-role
rules:
- apiGroups:
  - apps.webspheretraditional.io.ibm
  resources:
  - webspheretraditionalapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.webspheretraditional.io.ibm
  resources:
  - webspheretraditionalapplications/status
  verbs:
  - get
