# permissions for end users to edit webspheretraditionalapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webspheretraditionalapplication-editor-role
rules:
- apiGroups:
  - apps.webspheretraditional.io.ibm
  resources:
  - webspheretraditionalapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.webspheretraditional.io.ibm
  resources:
  - webspheretraditionalapplications/status
  verbs:
  - get
